# PyTorch Tutorial: GETTING STARTED
---

* **Reference**
   * [PyTorch](https://pytorch.org/)
   * [PyTorch Tutorials](https://pytorch.org/tutorials/)


## DEEP LEARNING WITH PYTORCH: [A 60 MINUTE BLITZ](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)
---

Goal of this tutorial:


* Understand PyTorch’s Tensor library and neural networks at a high level.
* Train a small neural network to classify images


### [What is PyTorch?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)
---

It’s **a Python-based scientific computing package** targeted at two sets of audiences:


* A replacement for NumPy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed


#### Tensors
---

**Tensors** are **similar to NumPy’s ndarrays**, with the addition being that Tensors can also be used **on a GPU to accelerate computing**.

In [1]:
from __future__ import print_function
import torch
print('PyTorch: ', torch.__version__)

PyTorch:  0.4.1


In [2]:
# Returns a tensor filled with uninitialized data.
x = torch.empty(5, 3)

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.float32


tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [3]:
"""
Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`
"""
x = torch.rand(5, 3)

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.float32


tensor([[0.6632, 0.5151, 0.1383],
        [0.9097, 0.2494, 0.2621],
        [0.0003, 0.3631, 0.1426],
        [0.9810, 0.7022, 0.5273],
        [0.1438, 0.3596, 0.0224]])

In [4]:
# Returns a tensor filled with the scalar value `0`.
x = torch.zeros(5, 3)

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.float32


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Data types


* See [torch.Tensor](https://pytorch.org/docs/stable/tensors.html)

In [5]:
# 64-bit integer (signed): torch.int64 or torch.long
x = torch.zeros(5, 3, dtype=torch.long)

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.int64


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Data로부터 tensor를 생성할 때 단 하나라도 float면 tensor의 dtype은 float가 된다.


**Default float**: `torch.float32`

In [6]:
# Constructs a tensor with :attr:`data`.
x = torch.tensor([[1, 2], [3.3333, 4]])

print(x.shape, x.dtype)
x

torch.Size([2, 2]) torch.float32


tensor([[1.0000, 2.0000],
        [3.3333, 4.0000]])

**Default integer**: `torch.int64`

In [7]:
x = torch.tensor([[1, 2], [3, 4]])

print(x.shape, x.dtype)
x

torch.Size([2, 2]) torch.int64


tensor([[1, 2],
        [3, 4]])

In [8]:
"""
Returns a Tensor of size :attr:`size` filled with ``1``.
By default, the returned Tensor has the same :class:`torch.dtype` and
:class:`torch.device` as this tensor.
"""      
x = x.new_ones(5, 3)    # new_* methods take in sizes

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.int64


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)    # new_* methods take in sizes

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.float64


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
"""
Returns a tensor with the same size as :attr:`input` that is filled with
random numbers from a normal distribution with mean 0 and variance 1.
"""
x = torch.randn_like(x)

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.float64


tensor([[-0.2464,  0.5177, -0.1272],
        [-1.8261, -0.1153, -0.5164],
        [-0.5677,  1.4731,  0.1790],
        [-0.7395,  0.2027,  0.1211],
        [ 0.9709, -0.0798, -1.7891]], dtype=torch.float64)

In [11]:
x = torch.randn_like(x, dtype=torch.float32)    # override dtype!

print(x.shape, x.dtype)
x

torch.Size([5, 3]) torch.float32


tensor([[-1.1010, -0.5376,  1.4320],
        [ 0.0491,  1.8868,  1.2266],
        [-1.8792, -0.5001,  0.3091],
        [ 0.6151,  1.2386,  0.1642],
        [ 0.2327, -0.7458, -2.2121]])

`x.size()`가 반환하는 `torch.Size`는 `x.shape`의 값(tensor의 size)과 동일하다.


또한, `torch.Size`는 `tuple`의 subclass이다.

In [12]:
"""
Returns the size of the :attr:`self` tensor. The returned value is a subclass of
:class:`tuple`.
"""
x.size()

torch.Size([5, 3])

In [13]:
x.shape

torch.Size([5, 3])

#### Operations
---

In [14]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [15]:
x + y

tensor([[1.4890, 1.5765, 1.2840],
        [1.3383, 0.9743, 1.3433],
        [0.8433, 0.2639, 1.2011],
        [1.2305, 1.1998, 0.9459],
        [0.8030, 1.1256, 1.1561]])

In [16]:
torch.add(x, y)

tensor([[1.4890, 1.5765, 1.2840],
        [1.3383, 0.9743, 1.3433],
        [0.8433, 0.2639, 1.2011],
        [1.2305, 1.1998, 0.9459],
        [0.8030, 1.1256, 1.1561]])

Providing an output tensor as argument.

In [17]:
result = torch.empty(5, 3)

torch.sub(x, y, out=result)

tensor([[-0.2083, -0.3859,  0.4118],
        [-0.3459,  0.0475,  0.3286],
        [ 0.6924,  0.0781,  0.5829],
        [ 0.3695, -0.0866,  0.3994],
        [-0.7977,  0.5535, -0.4311]])

Any operation that mutates a tensor **in-place** is **post-fixed with an `_`**. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [18]:
x

tensor([[0.6404, 0.5953, 0.8479],
        [0.4962, 0.5109, 0.8360],
        [0.7678, 0.1710, 0.8920],
        [0.8000, 0.5566, 0.6727],
        [0.0027, 0.8396, 0.3625]])

In [19]:
# In-place version of :meth:`~Tensor.add`
x.add_(y)

tensor([[1.4890, 1.5765, 1.2840],
        [1.3383, 0.9743, 1.3433],
        [0.8433, 0.2639, 1.2011],
        [1.2305, 1.1998, 0.9459],
        [0.8030, 1.1256, 1.1561]])

**Standard NumPy-like indexing** with all bells and whistles((특히 컴퓨터) 멋으로 덧붙이는 부가 기능)!


**bells and whistles**: additional features or accessories which are nonessential but very attractive  
이런 뜻이구나...

In [20]:
x[:, 1]

tensor([1.5765, 0.9743, 0.2639, 1.1998, 1.1256])

In [21]:
x[:, -2:]

tensor([[1.5765, 1.2840],
        [0.9743, 1.3433],
        [0.2639, 1.2011],
        [1.1998, 0.9459],
        [1.1256, 1.1561]])

In [22]:
x[...]

tensor([[1.4890, 1.5765, 1.2840],
        [1.3383, 0.9743, 1.3433],
        [0.8433, 0.2639, 1.2011],
        [1.2305, 1.1998, 0.9459],
        [0.8030, 1.1256, 1.1561]])

`torch.view`: resize/reshape

In [23]:
"""
Returns a tensor filled with random numbers from a normal distribution
with mean `0` and variance `1` (also called the standard normal
distribution).
"""
x = torch.randn(4, 4)

print(x.shape, x.dtype)
x

torch.Size([4, 4]) torch.float32


tensor([[-0.4977, -0.2150, -0.7608, -1.9818],
        [-0.7783,  0.2098, -0.8364, -0.6420],
        [ 0.2867, -0.7077,  0.2941, -0.0177],
        [ 1.8042, -0.4715,  2.5870,  0.7592]])

In [24]:
"""
Returns a new tensor with the same data as the :attr:`self` tensor but of a
different size.
"""
y = x.view(16)

print(y.shape, y.dtype)
y

torch.Size([16]) torch.float32


tensor([-0.4977, -0.2150, -0.7608, -1.9818, -0.7783,  0.2098, -0.8364, -0.6420,
         0.2867, -0.7077,  0.2941, -0.0177,  1.8042, -0.4715,  2.5870,  0.7592])

In [25]:
z = x.view(-1, 2)    # the size -1 is inferred from other dimensions

print(z.shape, z.dtype)
z

torch.Size([8, 2]) torch.float32


tensor([[-0.4977, -0.2150],
        [-0.7608, -1.9818],
        [-0.7783,  0.2098],
        [-0.8364, -0.6420],
        [ 0.2867, -0.7077],
        [ 0.2941, -0.0177],
        [ 1.8042, -0.4715],
        [ 2.5870,  0.7592]])

`.itme()`: get the value as a Python number from a tensor with one element

In [26]:
x = torch.randn(1)

"""
Returns the value of this tensor as a standard Python number. This only works
for tensors with one element.
"""
x.item()

0.4219002425670624

In [27]:
x = torch.randn(2, 2)

"""
Returns the tensor as a (nested) list. For scalars, a standard
Python number is returned, just like with :meth:`~Tensor.item`.
"""
x.tolist()

[[0.2932477295398712, -1.2227989435195923],
 [-0.37361589074134827, 0.3924306035041809]]

#### NumPy Bridge
---

**Converting a Torch Tensor to a NumPy array and vice versa** is a breeze(식은 죽 먹기).


The Torch Tensor and NumPy array will **share their underlying memory locations**, and **changing one will change the other**.


All the Tensors on the CPU **except a CharTensor** support converting to NumPy and back.

In [28]:
a = torch.ones(5)

print(a.shape, a.dtype)
a

torch.Size([5]) torch.float32


tensor([1., 1., 1., 1., 1.])

In [29]:
"""
Returns :attr:`self` tensor as a NumPy :class:`ndarray`. This tensor and the
returned :class:`ndarray` share the same underlying storage. Changes to
:attr:`self` tensor will be reflected in the :class:`ndarray` and vice versa.
"""
b = a.numpy()

print(b.shape, b.dtype)
b

(5,) float32


array([1., 1., 1., 1., 1.], dtype=float32)

`a`와 `b`는 동일한 기본 저장소를 공유하기 때문에 Torch tensor `a`의 값을 변경하면 NumPy array `b`의 값도 같이 변한다.

In [30]:
a.add_(1)

print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


반대의 경우도 마찬가지!

In [31]:
import numpy as np

a = np.ones(5)
# Creates a :class:`Tensor` from a :class:`numpy.ndarray`.
b = torch.from_numpy(a)
np.add(a, 4, out=a)

print(a)
print(b)

[5. 5. 5. 5. 5.]
tensor([5., 5., 5., 5., 5.], dtype=torch.float64)


#### CUDA Tensors
---

Tensors can be moved onto any device using the `.to` method (or `CUDA device object`).

In [32]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    x = torch.ones(2, 2)                   # on CPU
    print(x)
    y = torch.zeros(2, 2, device=device)    # directly create a tensor on GPU
    print(y)
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    print(x)
    z = x * 2 + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[2., 2.],
        [2., 2.]], device='cuda:0')
tensor([[2., 2.],
        [2., 2.]], dtype=torch.float64)
