# Save and Load Arrays to a Binary file in NumPy Format
---

* **NPY format**


`.npy`, `.npz`


**A simple format for saving numpy arrays to disk** with the full information about them.


The `.npy` format is **the standard binary file format in NumPy** for persisting a single arbitrary NumPy array on disk. The format stores **all of the shape and dtype information necessary to reconstruct the array correctly** even on another machine with a different architecture. The format is designed to be as simple as possible while achieving its limited goals.


The `.npz` format is the standard format for persisting **multiple NumPy arrays** on disk. A `.npz` file is **a zip file** containing multiple `.npy` files, one for each array. When opening the saved `.npz` file with load a **NpzFile object** is returned. This is **a dictionary-like object** which can be queried for its list of arrays (with the `.files` attribute), and for the arrays themselves.


* **Reference**
   * [NumPy v1.15 Manual](https://docs.scipy.org/doc/numpy/index.html)
   * [numpy.lib.format](https://docs.scipy.org/doc/numpy/reference/generated/numpy.lib.format.html#module-numpy.lib.format)

In [1]:
import numpy as np

In [2]:
array_int = np.array([[1, 2], [3, 4]])

print(array_int.shape, array_int.dtype)

(2, 2) int32


In [3]:
np.save(r'data/array_int.npy', array_int, allow_pickle=False)

In [4]:
array_float = np.array([[1., 2.], [3., 4.]])

print(array_float.shape, array_float.dtype)

(2, 2) float64


## Save Arrays
---

```python
numpy.save(file, arr, allow_pickle=True, fix_imports=True)
```

> Save an array to a binary file in NumPy `.npy` format.

In [5]:
np.save(r'data/array_float.npy', array_float)

```python
numpy.savez(file, *args, **kwds)
```

> Save several arrays into a single file in uncompressed `.npz` format.

In [6]:
np.savez(r'data/arrays_with_default_names.npz', array_int, array_float)

Arrays will be saved in the file with the keyword names. e.g. `i`, `f`

In [7]:
np.savez(r'data/arrays_with_keyword_names.npz', i=array_int, f=array_float)

In [8]:
np.savez_compressed(r'data/arrays_compressed.npz', array_int, array_float)

## Load Arrays
---

```python
numpy.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')
```

> Load arrays or pickled objects from `.npy`, `.npz` or pickled files.


Load an array from `.npy` file.

In [9]:
arr_i = np.load(r'data/array_int.npy')

print(arr_i.shape, arr_i.dtype)

(2, 2) int32


In [10]:
arr_i

array([[1, 2],
       [3, 4]])

In [11]:
arr_f = np.load(r'data/array_float.npy')

print(arr_f.shape, arr_f.dtype)

(2, 2) float64


In [12]:
arr_f

array([[1., 2.],
       [3., 4.]])

Load arrays from `.npz` file.

In [13]:
arrays_with_default_names = np.load(r'data/arrays_with_default_names.npz')

type(arrays_with_default_names)

numpy.lib.npyio.NpzFile

In [14]:
len(arrays_with_default_names)

2

In [15]:
arrays_with_default_names.files

['arr_0', 'arr_1']

In [16]:
arrays_with_default_names['arr_0']

array([[1, 2],
       [3, 4]])

In [17]:
arrays_with_default_names['arr_1']

array([[1., 2.],
       [3., 4.]])

In [18]:
arrays_with_keyword_names = np.load(r'data/arrays_with_keyword_names.npz')

arrays_with_keyword_names.files

['i', 'f']

In [19]:
arrays_with_keyword_names['i']

array([[1, 2],
       [3, 4]])

In [20]:
arrays_with_keyword_names['f']

array([[1., 2.],
       [3., 4.]])

In [21]:
arrays_compressed = np.load(r'data/arrays_compressed.npz')

arrays_compressed.files

['arr_0', 'arr_1']

In [22]:
arrays_compressed['arr_0']

array([[1, 2],
       [3, 4]])

In [23]:
arrays_compressed['arr_1']

array([[1., 2.],
       [3., 4.]])

## RcppCNPy
---

NumPy is a popular package for scientific / numeric computing with Python. It uses an internal file to store vectors and matrices.


Sometimes we want to read (or write) these files with languages other than Python. The small CNPy library on GitHub permits this from C++, and by relying on Rcpp we can easily bring this to R.


※ The standard mode of R for storing numbers is **double**. In this mode, every number uses 64 bits of memory.


* **Reference**
   * [RcppCNPy](http://dirk.eddelbuettel.com/code/rcpp.cnpy.html)
   * [RcppCNPy GitHub](https://github.com/eddelbuettel/rcppcnpy)

```r
install.packages("RcppCNPy")
library("RcppCNPy")

# Do not use integer types.
# arr_i = npyLoad("D:\\Jin\\workspace\\study\\jin_study\\numpy\\data\\array_int.npy", "integer")
arr_f = npyLoad("D:\\Jin\\workspace\\study\\jin_study\\numpy\\data\\array_float.npy")
```